### ISSUE TITLE
`@OneToMany` and `@ManyToOne` annotations link columns incorrectly

### ISSUE THREAD

**Issue by thejhh** [heusalagroup/fi.hg.core#63]
This happens if multiple entities use same property names. The way we implemented the linking based on column and property names was a hack. 

The root cause was trying to make this implementation as similar to Java as possible, but it is just not possible, since TypeScript annotations cannot detect the type of the property at runtime. In Java, the framework can know that the type of the property is specific entity. In TypeScript this is not possible at runtime.

I will be fixing this issue by implementing `@ManyToOne(tableName : string)` or `@ManyToOne(entity: Entity)` (the constructor) addition where the target to where the property is linking is known at runtime. The table name option is there for the case where circular dependencies might exist.

### TODO

* [x] Memory only persister fix (wasn't broken)
* [x] PostgreSQL persister fix (fixed)
* [x] MySQL fix pending

**Comment by thejhh** [comment]
There must be a test to verify this issue.

**Comment by thejhh** [comment]
We have a test and fix for PostgreSQL now. However, it does not work on MySQL, since there is no equality operator for JSON available. I will leave MySQL support as it is for now; the current project I am working on does not need it. (In few days I will be working on one that does, so fix comes then.)

See also https://stackoverflow.com/questions/70993552/how-to-return-distinct-values-in-a-json-arrayagg-when-using-json-object
